var en = {
	"advanced" :  "advanced",
	"running_status" :  "Running Status",
	"system_mgmt" :  "System",
	  "dev_mgmt" :  "Device",
		"default_config" :  "Default Factory Config",
		"backup_config" :  "Backup Config",
		"restore_config" :  "Restore Config",
		"reboot" :  "Reboot OLT",
	  "diagonose" :  "Diagnose",
	  "remote_mgmt" :  "Remote",
		"outbound" :  "Outbound Interface",
		"inbound" :  "Inbound Interface",
	  "upgrade" :  "Upgrade",
		"firmware" :  "Firmware",
		"system" :  "System",
	  "time" :  "Time Setting",
	"pon_mgmt" :  "PON Port",
	  "onu_allow" :  "ONU Allow List",
	  "onu_deny" :  "ONU Deny List",
	  "sla_cfg" :  "Bandwidth",
	  "pon_setting": "PON Setting",
	"onu_mgmt" :  "ONU Device",
      "onu_basic_info" :  "ONU Basic Info",
      "onu_port_cfg":  "ONU Port Config",
	"swport_mgmt" :  "Switch Port",
	  "port_info" :  "Port Info",
	  "perf_info" :  "Performance",
	  "port_cfg" :  "Port Config",
		"vlan_cfg" :  "VLAN Config",
		"stormctrl_cfg" :  "Stormctrl",
		"port_mirror" :  "Port Mirror",
	"layer2_mgmt" :  "layer2",
	  "vlan_mgmt" :  "VLAN",
	  "mac_mgmt" :  "MAC Address Table",
	"protocol_mgmt" :  "Protocol",
	  "rstp" :  "rstp",
	  "tips": "Notice",
	"create" :  "Create",
	"destroy":  "Delete",
	"add" :  "Add",
	"delete" :  "Delete",
	"modify" :  "Modify ",
	"find" :  "Find",
	"apply" :  "Apply",
	"cancel" :  "Cancel",
	"config" :  "Setting ",
	"enable" :  "Enable",
	"disable" :  "Disable",
	"full" :  "Full",
	"half" :  "Half",
	"type" :  "Type",
	"using" :  "Enable",
	"forbidden" :  "Disable",
	"st_success": "success",
	"st_fail": "failed",
    "range":  "Range",
	"onu_info": "ONU Info",
	
	"upgrade_firmware":" upgrade firmware",
	"upgrade_system": " upgrade system",
	"pon_auth":"PON Authorize",
	"auth_type": "Auth type",
	"auth_mode": "Auth mode",
	"macaddr" :  "MAC",
	"macmask" :  "MAC Mask",
	"ponports" :  "PON Ports",
	"geports" :  "GE Ports",
	"xgeports" :  "XGE Ports",
	"feports" :  "FE Ports",
	"build_time" :  "Build Time",
	"product_name" :  "Product Model",
	"sys_ver" :  "System Version",
	"fw_ver" :  "Firmware Version",
	"hw_ver" :  "Hardware Version",
	"voip":"VoIP",
	"wlan":"WLAN",
	"usb":"USB",
	"catv":"CATV",
	
	"cpu_usage" :  "CPU Usage",
	"memory_usage" :  "Memory Usage",
	
	"port_id" :  "Port ID",
	"status"  :  "Status",
	"online" :  "Online",
	"offline" :  "Offline",
	
	"admin_status" :  "Admin Status",
	"link_status"  :  "Link Status",
	"link_up" :  "Link UP",
	"link_down" :  "Link Down",
	"auto_neg"  :  "Auto Negonation",
	"speed"  :  "Speed",
	"duplex"  :  "Duplex",
	"flow_ctrl"  :  "Flow Control",
	"pvid"  :  "Default VLAN",
	"media" :  "Medium",
	"copper" :  "Copper" ,
	"fiber" :  "Fiber",
    "erate": "Egress rate",
    "irate": "Ingress rate",
	
	"ipaddr" :  "IP Address",
	"ipmask" :  "IP Mask",
	"mtu" :  "MTU",
	"interface" :  "Interface",
	"count" :  "Count",
	"pktsize" :  "Packet Size",
	"timeout" :  "Timeout",
	
	"rcvpkt" :  "Rx Packets",
	"rcvbytes" :  "Rx Bytes",
	"transpkt" :  "Tx Packets",
	"transbytes" :  "Tx Bytes",
	
	"current_time" :  "Current Time",
	"run_time" :  "Running Time",
	"days" :  "Day",
	"hours" :  "Hour",
	"mins" :  "Min",
	"secs" :  "Sec",
    
    "search_by_macaddr":  "Enter mac address to find ONU, support partial match search",
	"onu_id" :  "ONU ID",
	"onu_name": "Name",
	"onu_desc": "Description",
    "auth_state" :  "Auth State",
    "tips_cfm_onu": "the ONU have confirmed, Click to cancel confirm status",
    "tips_auth_state":  "Are you sure you want to authenticate the current ONU?",
    "tips_unauth_state":  "Are you sure you want to lift the current state of the ONU Certification?",
    "tips_n_cfm_onu": "The ONU not confirmed, Click to confirm ONU",
	"tips_authstate_error":  "ONU is not online and cannot be operated",
    "tips_onu_btn_detail": "show the ONU detail informations",
    "tips_page_refresh":  "Refresh the current page",
    "click":  "Click",
    "onudeny_add_tips":  "Click the Add button to manually add the ONU in deny list,need parameters MAC address(required), descriptor(optional)",
    "onudeny_del_tips":  "Remove the current ONU from the deny list",
	"tips_onu_btn_del": "Delete ONU",
	"tips_onu_btn_rej": "Reject ONU to blacklist",
	"tips_onu_restart": "Restart ONU",
	"register_time" :  "Register Time",
    "rtt" :  "Round Trap Time",
    "deregister_onu": "Deregister ONU",
    "set_fec_mode": "Change fec mode",
    "confirm_reboot_onu": "Confirm to reboot onu",
    "confirm_deresgester": "Confirm to deregister onu",
    "confirm_change_fecmode": " Confirm to change fec mode",
	
	"retry" :  "Retry Counts",
	
	"sla_type" :  "Sla Type",
	"fix" :  "Fix",
	"assure" :  "Assure",
	"max" :  "Max",
    "fix_range_err": "Fixed bandwidth out of range",
    "assure_range_err": "Assured bandwidth out of range",
    "max_range_err": "Maximum bandwidth out of range",
    "fix_param_err": "Fixed bandwidth cannot exceed the assured or maximum bandwidth",
    "assure_param_err": "Assured bandwidth cannot exceed the maximum bandwidth",
	
	"auth_mode" :  "Auth Mode",
	"onu_type" :  "ONU Type",
	"vendor" :  "Vendor",
	"sn_model" :  "SN model",
	"chip_model": "Chip model",
	"onu_chip" :  "Chip vendor",
	"software_ver": "Software versions",
	"hardware_ver": "Hareware versions",
	
	"tips_del_onu": "Please confirm to delete ONU",
	"tips_add_deny_onu": "Please confirm to add ONU to onu deny list",
	
	
	"port_type" :  "Port Type",
	"vlan_mode" :  "VLAN Mode",
	"tagged" :  "Tagged",
	"untagged" :  "Untagged",
	
	"stormctrl" :  "Storm Control",
	"broadcast" :  "Broadcast",
	"multicast" :  "Multicast",
	"unicast" :  "Unicast",
	
	"mirror" :  "Mirror",
	"src_port" :  "Source Port",
    "dst_port" :  "Destination Port",
    "choose":  "Choose",
	
	"age" :  "Age Time",
	"mac_type" :  "MAC Address Type",
	"blackhole" :  "Blackhole",
	"static" :  "Static",
	"dynamic" :  "Dynamic",
    "vlan_id" :  "VLAN ID",
    "tips_del_mac": "Please confirm to delete mac address",
    "add_mac": "Add MAC",
    "flush_mac": "Flush MAC",
    "flush_way": "Flush method",
	
	"flush" :  "Flush",
    "desc" :  "Description",
    "loadmore":  "Load More",
    "vlan_list":  "VLAN List",
    "detail":  "Detail",
    "query_method":  "Query Method",
    "mac_index":  "Index",
	
	"rstp_mode":  "Rstp Mode",
	"rb_priority":  "Root Bridge Priority",
	"rb_address":  "Root Bridge Address",
	"db_priority":  "Designated Bridge Priority",
	"db_address":  "Designated Bridge Address",
	"max_age":  "BPDU Max Age",
	"hello_time":  "BPDU Hello Time",
	"forward_delay":  "Forward Delay",
	"transmit_hold_count":  "BPDU Hold Count",
	"root_path_cost":  "Root Path Cost",
	
	"port_priority":  "Priority",
	"port_path_cost":  "Path Cost",
	"edge_status":  "Edge Status",
	"admin_link_type":  "Admin LinkType",
	"oper_link_type":  "Oper LinkType",
	"port_role":  "Role",
	"port_state":  "Status",
	"auto":  "Auto",
	"p2p":  "P2P",
	"shared":  "Shared",
    
    "interface_cfg":  "Configurable options for different interface",
    "bound_tips":  "Outbound or inbound interface can be configured the IP address and IP mask",
    "add_inbound_tips":  "Add only add inbound, the IP address,IP mask and VLAN ID must be configured",
	
	"http_login_timeout": "Login timeout, Please again login the device",
	"service_user_password_fail": "The username or password check failed",
	"login_success": "Welcome",
	"login_user": "Login",
	"password_length_fail": "the range of the length of the password is 5-16 and it can't be use space / \\ \' \" charactor, Please check!",
	"username_length_fail": "the range of the length of the username is 5-16 and it can't be use special charactior, Please check!",
	"login_out": "Logout successfully",
	"login_page_login_hit": "Please Login EPON OLT for Management",
	"login_timeout": "Login timeout, Please Login",
	"illegal_login_info": "Illegal Login Information",
	"logout": "Sign out",
    "no_support": "Not support now",
	"company_info": "Company information & Copyright information",
	"setting_ok":  "Setting success",
    "setting_fail":  "Setting failed",
    "tips_create_vlan": "Press to create vlan, and add ports",
	"create_vlan_info": "Create vlan success，Please waiting for apply",
	"delete_vlan_hit": "It will delete this vlan, please check",
	"vlanid_range_hit": "The range of VLAN ID is 1-4094",
	"not_find_vlan": "There's not VLAN",
	"restore_config_fail": "Restore the OLT configuration failed",
	"restore_config_succ": "Restore the OLT configuration success, and take it effect as reboot",
    "restore_succ_reboot": "Restore the OLT configuration success，reboot OLT now",
	"save_succ": "Save configuration success",
	"save_config": "Save configuration",
	"restore_file_nr": "The file format is incorrect",
	"file_not_select": "There's no file",
	"file_click": "Click to select file",
	"default_config_fail": "Default the OLT configuration failed",
	"def_cfg_succ": "Default the OLT configuration sucess, the system is reboot now...",
	"reboot_olt_hit": "Please assure to reboot OLT",
	"def_cfg_hit": "Defualt the OLT configuration, the system will discard the configuration and auto reboot",
	"def_cfg_info": "Notice:  After default the OLT configuration, device will be the factory config",
	"save_cfg_confirm": "All current settings have been saved and confirmed",
	"save_cfg_info": "Notice:  Save all current configurations and write them to the device",
	"res_cfg_info": "Notice:  You can restore the configuration file",
	"bkup_cfg_info": "Notice:  You can backup the configuration file",
	"reboot_olt": "Notice:  Click the button, you can restart the OLT",
	
	"sys_upgrade_fail": "Upgrade system failed",
	"sys_upgrade_succ": "Upgrade system success, take it effect as restart OLT",
	"fw_upgrade_fail": "Upgrade firmware failed",
    "fw_upgrade_succ": "Upgrade firmware success, take it effect as restart OLT",
    "upgrade_buzy": "Upgrade failed, other user upgrading",
    "file_header_error": "Upgrade failed, the file header is not correct!",
    "upgrade_success": "Upgrade Success, Rebooting device",
	
	"get_data_fail": "Get the data failed",
	
	"onu_cfg": "ONU Setting",
	"onu_bw_fail_info": "There's no any bandwidth information in this port",
	"sys_run_time": "System running time",
	
	"hw_status": "Hardware status",
	"sys_info": "System informations",
	"clk_port_cfg": "Click to setting port",
	"ge_port_info": "GE infomations",
	"clk_onu_allow": "Click to setting ONU-allow-list",
	"registered_onu": "Registered: ",
	"pon_info": "PON Informations",
	"rstp_port_pri": "Setting rstp port priority",
	"rstp_global_info": "Setting rstp gloabal",
	"rstp_p_pri_b": "Setting port priority",
	
	"rstp_p_info": "Rstp port",
	"rstp_b_info": "Rstp bridge",
	
	"no_inb_info": "None outbound interface",
	"oub_con_fail": "Connect outbound interface failed",
	
	"if_sure": "Please confirm",
	
	"flush_page_retry": "Please refresh and try it again...",
	"sw_port_cfg": "Switch port basic configuration",
	"no_more_data": "No more data...",
	"no_onu_info": "No more ONU information...",
    "add_to_deny": "Add to deny list",
    "confirm_del_deny":  "Confirm delete this ONU from deny list",
	"del_onu": "Delete ONU",
	"clk_cancel_cfrm": "Click to cancel confirm",
	"clk_cfrm": "Click to confirm",
    "input_desc": "Description",
    "onu_offline_tips":  "The ONU is offline can not be restarted",
	
	"zero_auto_": "if 0 or none:  Auto assign",
	"manual_bind": "Manual add ONU",
    "reboot_onu": "Reboot ONU",
    "ipaddr_error":  "IP address format error",
    "ipmask_error": "IP mask format error",
	
	"lang" :  "Language",
	"modify_tips":  "There's none modify",
	"param_mac": "MAC address parameter error",
	"param_onuid": "ONU ID illegal",
	"param_error": "illegal parameter",
	"time_set": "Time",
	"manual_s":  "Manual",
	"time_days": "Day",
	"time_year": "Year",
	"time_month": "Month",
	"time_day": "Day",
	"time_hour": "Hour",
	"time_min": "Minute",
	"time_sec": "Second",
	"time_get_serv": "Get device time",
	"time_set_local": "Update local time",
	"notice_time_sync":  "Notice:  WebGUI's time display maybe different from server, you can press this button for synchronization",
	"update_time": "Update time",
	"diff_type_cfg": "the options of different type",
    "select_all":  "Select All",
    "clear_all":  "Clear All",
    
    "onu_port_config": "ONU port configuration",
    "onu_vlan_mode_cfg": "ONU port VLAN mode configuration",
    "onu_port_id": "ONU port ID",
    "onu_add_translate": "add vlan translate for ONU",
    "onu_del_translate": "delete vlan translate from ONU",
    "onu_add_trunk": "add vlan trunk for ONU",
    "onu_del_trunk": "delete vlan trunk from ONU",
    "vlan_pri_param_error": "VLAN priority parameters incorrect",
    "translate_exits": " VLAN translate is existed",
    "trunk_vlanid_range_error": "VLAN list exceed maximum configurable",
    "op_id": "ONU port ID",
    "rlds_opt": "down stream rate limit",
    "rl_cir": "CIR",
    "rl_pir": "PIR",
    "rlus_opt": "up stream rate limit",
    "loopdetect": "loop detect",
    "start_vlan_id": "Start VLAN",
    "end_vlan_id": "End VLAN",
    "op_vlan_mode": "ONU port VLAN mode",
    "def_vlan_id": "default VLAN",
    "def_vlan_pri": "default VLAN Priority",
    "new_vlan_pri": "VLAN Priority",
    "vlan_pri": "VLAN priority",
    "bandwidth":  "Band width",
    "rstp_tips_disable": "Global RSTP bridge is not enabled and can not proceed this setting",

    "work_temprature": "work temperature",
    "work_voltage": "work voltage",
    "transmit_bias":  "transmit bias",
    "transmit_power":  "transmit power",
    "receive_power": "receive power",
    "refresh":  "Refresh",
    "onu_optical_diagnose": "ONU optical diagnose",
    "diag_tools_type": "Diagnose tools type",
    "dest_ping_ip":  "Destination IP",
    "diag_ping_intf": "Out interface",
    "diag_ping_count":  "PING Count",
    "diag_ping_pktsize":  "PING packet size",
	"diag_type":  "Ping test",
	"start":  "Start",
	"select_timezone":  "Select Timezone",
	"switch_display": "Switch display mode",
	"service": "Service",
	"click_often":"Click too often",
	"ntp_ipaddr1": "Preferred IP address",
	"ntp_ipaddr2": "Alternate IP address",
	"ntp_gettime": "Get time automatically",
	"update_frequency": "Update frequency",
	"alarm": "Alarm",
	"alarm_info": "Alarm information",
	"port_vlan":"Port VLAN",
	"pv_vlist_tips": 'The vlan list can be a single number or a continuous range. The start and end points of the range are separated by "-", and each item is separated by ",".',
	"pv_vmode_tips": "The vlan mode is allowed to be modified only when the port type is 'hybrid'.",
	"add_vlan_list":"Add the port to the specified VLAN",
	"del_vlan_list":"Remove the port from the specified VLAN",
	"svlan_pri": "svlan priority",
	"batch_mgmt_onu":"ONU Batch management",
	"exit_batch_onu": "Exit batch management",
	"no_select_onu":"No ONU is currently selected",

	"onu_batch_upgrade":"ONU Batch Upgrade",
	"onu_upgrade_tips":"The upgrade type name only consists of English letters, numbers and \" - \"",
	"upgrade_type":"Upgrade type",
	"upgrade_type_mgmt":"Upgrade type management",
	"onu_bind_upgrade_type":"ONU binding upgrade type",
	"current_upgrade_type":"Currently upgrade types",
	"select_upgrade_type":"Select upgrade type",
	"no_upgrade_type":"No currently available type of upgrade",
	"add_onu_type":"Add an ONU upgrade type",
	"del_onu_type":"Delete ONU upgrade type",
	"onu_upgrade_start":"The upgrade has started, The upgrade information is displayed on the alarm information page.",

	"igmp": "IGMP",
	"fast_leave":"fast leave",
	"protocol_policy":"protocol policy",
	"group_aging_time":"group aging time",
	"robustness":"robustness",
	"gen_response_time":"general response time",
	"gen_query_interval":"general query interval",
	"sp_response_time":"special response time",
	"sp_query_interval":"special query interval",
	"sp_query_number":"special query number",
	"multi_ip":"multicast IP",
	"host_portlist":"port members",
	"mc_unknown_policy":"multicast unknown policy",
	"transparent":"transparent",
	"discard":"discard",
	"mvlan":"multicast VLAN",
	"router_portlist":"router port",
	"program":"program",
	"program_s":"program start",
	"program_e":"program end",
	"mode":"Mode",
	"query_src_ip":"query source IP",
	"query_src_mac":"query source MAC",
	"vid":"multicast vlan",
	"action":"multicast type"
}

export default en