var en = {
    advanced: " Advanced ",
    running_status: " Running Status",
    system_mgmt: " System",
    dev_mgmt: " Device",
    default_config: " Default Factory Config",
    backup_config: " Backup Config",
    restore_config: " Restore Config",
    reboot: " Reboot",
    diagonose: " Diagnose",
    remote_mgmt: " Network Interface",
    outbound: " Outbound Interface",
    inbound: " Inbound Interface",
    upgrade: " Upgrade",
    firmware: " Firmware",
    system: " System",
    time: " Time Setting",
    pon_mgmt: " PON Port",
    onu_allow: " ONU Table",
    onu_deny: " ONU Deny List",
    sla_cfg: " Upstream Bandwidth",
    pon_setting: " PON Setting",
    onu_mgmt: " ONU Device",
    onu_basic_info: " ONU Basic Info",
    onu_port_cfg: " ONU Port Config",
    swport_mgmt: " Switch Port",
    port_info: " Port Info",
    perf_info: " Performance",
    port_cfg: " Port Config",
    vlan_cfg: " VLAN Config",
    stormctrl_cfg: " Stormctrl",
    port_mirror: " Port Mirror",
    layer2_mgmt: " Switch",
    vlan_mgmt: " VLAN",
    mac_mgmt: " MAC Address Table",
    protocol_mgmt: " Protocol",
    rstp: " RSTP",
    tips: " Notice",
    create: " Create",
    destroy: " Delete",
    add: " Add",
    delete: " Delete",
    modify: " Modify ",
    find: " Find",
    apply: " Apply",
    set: " Set ",
    commit: "Commit",
    cancel: " Cancel",
    config: " Setting ",
    enable: " Enable",
    disable: " Disable",
    full: " Full",
    half: " Half",
    type: " Type",
    using: " Enable",
    forbidden: " Disable",
    st_success: " Success",
    st_fail: "  Failed",
    range: " Range",
    onu_info: " ONU Info",
    user_mgmt: " User Managerment",
    user: " User ",
    user_name: " User Name",
    password: " Password ",
    modify_user_pwd: " Modify current user password",
    title: "  Title",
    key: "  Key",
    info: "  Information",
    download: " Download",
    on: " ON",
    off: " OFF",
    advanced_setting: "Advanced Setting",
    save: " Save ",

    upgrade_firmware: " Upgrade Firmware",
    upgrade_system: " Upgrade System",
    pon_auth: " PON Authorize",
    auth_type: " Auth Type",
    auth_mode: " Auth Mode",
    macaddr: " MAC",
    macmask: " MAC Mask",
    ponports: " PON Ports",
    geports: " GE Ports",
    xgeports: " XGE Ports",
    feports: " FE Ports",
    build_time: " Build Time",
    product_name: " Product Model",
    sys_ver: " System Version",
    fw_ver: " Firmware Version ",
    hw_ver: " Hardware Version",
    voip: " VoIP",
    wlan: " WLAN",
    usb: " USB",
    catv: " CATV",

    cpu_usage: " CPU Usage",
    memory_usage: " Memory Usage",

    port_id: " Port ID",
    status: " Status",
    online: " Online",
    offline: " Offline",

    admin_status: " Admin Status",
    link_status: " Link Status",
    link_up: " Link UP",
    link_down: " Link Down",
    auto_neg: " Auto Negonation",
    speed: " Speed",
    duplex: " Duplex",
    flow_ctrl: " Flow Control",
    pvid: " Default VLAN",
    media: " Medium",
    copper: " Copper",
    fiber: " Fiber",
    erate: " Egress Rate",
    irate: " Ingress Rate",

    ipaddr: " IP Address",
    ipmask: " IP Mask",
    mtu: " MTU",
    interface: " Interface",
    count: " Count",
    pktsize: " Packet Size",
    timeout: " Timeout",

    rcvpkt: " Rx Packets",
    rcvbytes: " Rx Bytes",
    transpkt: " Tx Packets",
    transbytes: " Tx Bytes",

    current_time: " Current Time",
    run_time: " Running Time",
    days: " Day",
    hours: " Hour",
    mins: " Min",
    secs: " Sec",

    search_by_macaddr:
        " Enter the MAC address or Name to search for ONU. Supports partial matching and Regular Expressions.",
    onu_id: " ONU ID",
    onu_name: " Name",
    onu_desc: " Description",
    auth_state: " Auth State",
    tips_cfm_onu: " the ONU have confirmed, Click to cancel confirm status",
    tips_auth_state: " Are you sure you want to authenticate the current ONU?",
    tips_unauth_state:
        " Are you sure you want to lift the current state of the ONU Certification?",
    tips_n_cfm_onu: " The ONU not confirmed, Click to confirm ONU",
    tips_authstate_error: " ONU is not online and cannot be operated",
    tips_onu_btn_detail: " show the ONU detail informations",
    tips_page_refresh: " Refresh the current page",
    click: " Click",
    onudeny_add_tips:
        " Click the Add button to manually add the ONU in deny list,need parameters MAC address(required), descriptor(optional)",
    onudeny_del_tips: " Remove the current ONU from the deny list",
    tips_onu_btn_del: " Delete ONU",
    tips_onu_btn_rej: " Reject ONU to blacklist",
    tips_onu_restart: " Restart ONU",
    register_time: " Register Time",
    rtt: " Round Trap Time",
    deregister_onu: " Deregister ONU",
    set_fec_mode: " Change Fec Mode",
    confirm_reboot_onu: " Confirm to reboot onu",
    confirm_deresgester: " Confirm to deregister onu",
    confirm_change_fecmode: "  Confirm to change fec mode",

    retry: " Retry Counts",

    sla_type: " Sla Type",
    fix: " Fix",
    assure: " Assure",
    max: " Max",
    fix_range_err: " Fixed bandwidth out of range",
    assure_range_err: " Assured bandwidth out of range",
    max_range_err: " Maximum bandwidth out of range",
    fix_param_err:
        " Fixed bandwidth cannot exceed the assured or maximum bandwidth",
    assure_param_err: " Assured bandwidth cannot exceed the maximum bandwidth",

    auth_mode: " Auth Mode",
    onu_type: " ONU Type",
    dev_type: " Device Type ",
    vendor: " Vendor",
    sn_model: " SN Model",
    chip_model: " Chip Model",
    onu_chip: " Chip Vendor",
    software_ver: " Software Versions",
    hardware_ver: " Hareware Versions",

    tips_del_onu: " Please confirm to delete ONU",
    tips_add_deny_onu: " Please confirm to add ONU to onu deny list",

    port_type: " Port Type",
    vlan_mode: " VLAN Mode",
    tagged: " Tagged",
    untagged: " Untagged",

    stormctrl: " Storm Control",
    broadcast: " Broadcast",
    multicast: " Multicast",
    unicast: " Unicast",
    stormctrl_tips: "All 0 means to turn off storm control",

    mirror: " Mirror",
    choose: " Select",

    age: " Age Time",
    mac_type: " MAC Address Type",
    blackhole: " Blackhole",
    static: " Static",
    dynamic: " Dynamic",
    vlan_id: " VLAN ID",
    tips_del_mac: " Please confirm to delete mac address",
    add_mac: " Add MAC",
    flush_mac: " Flush MAC",
    flush_way: " Flush Method",

    flush: " Flush",
    desc: " Description",
    loadmore: " Load More",
    vlan_list: " VLAN List",
    detail: " Detail",
    query_method: " Query Method",
    mac_index: " Index",

    rstp_mode: " Rstp Mode",
    rb_priority: " Root Bridge Priority",
    rb_address: " Root Bridge Address",
    db_priority: " Designated Bridge Priority",
    db_address: " Designated Bridge Address",
    max_age: " BPDU Max Age",
    hello_time: " BPDU Hello Time",
    forward_delay: " Forward Delay",
    transmit_hold_count: " BPDU Hold Count",
    root_path_cost: " Root Path Cost",

    port_priority: " Priority",
    port_path_cost: " Path Cost",
    edge_status: " Edge Status",
    admin_link_type: " Admin LinkType",
    oper_link_type: " Oper LinkType",
    port_role: " Role",
    port_state: " Status",
    auto: " Auto",
    p2p: " P2P",
    shared: " Shared",

    interface_cfg: " Configurable options for different interface",
    bound_tips:
        " Outbound or inbound interface can be configured the IP address and IP mask",
    add_inbound_tips:
        " Add only add inbound, the IP address,IP mask and VLAN ID must be configured",

    http_login_timeout: " Login timeout, Please again login the device",
    service_user_password_fail: " The username or password check failed",
    login_success: " Welcome",
    current_user_list: " Currently existing user list",
    login_user: " Login",
    password_length_fail:
        " the range of the length of the password is 5-16 and it can't be use space / \\ ' \"  charactor, Please check!",
    username_length_fail:
        " the range of the length of the username is 5-16 and it can't be use special charactior, Please check!",
    pwd_not_match: " Inconsistent password entered twice",
    current_pwd: " Current Password",
    new_pwd: " New Password",
    cfm_pwd: " Confirm Password",
    user_level: " User Rights",
    user_reenter: " Maximum Logins",
    modify_success:
        " The modification is successful, please log in again with the new password.",
    login_out: " Logout successfully",
    login_page_login_hit: " Please Login EPON OLT for Management",
    login_timeout: " Login timeout, Please Login",
    illegal_login_info: " Illegal Login Information",
    logout: " Sign Out",
    no_support: " Not support now",
    company_info: " Company information & Copyright information",
    setting_ok: " Setting success",
    delete_ok: "Delete success",
    delete_fail: "Delete failed",
    setting_fail: " Setting failed",
    tips_create_vlan: " Press to create vlan, and add ports",
    create_vlan_info: " Create vlan success，Please waiting for apply",
    delete_vlan_hit: " It will delete this vlan, please check",
    vlanid_range_hit: " The range of VLAN ID is 1-4094",
    not_find_vlan: " There's not VLAN",
    restore_config_fail: " Restore the OLT configuration failed",
    restore_config_succ:
        " Restore the OLT configuration success, and take it effect as reboot",
    restore_succ_reboot:
        " Restore the OLT configuration success，reboot OLT now",
    save_succ: " Save configuration success",
    save_config: " Save configuration",
    restore_file_nr: " The file format is incorrect",
    file_not_select: " There's no file",
    file_click: " Click to select file",
    default_config_fail: " Default the OLT configuration failed",
    def_cfg_succ:
        " Default the OLT configuration sucess, the system is reboot now...",
    reboot_olt_hit: " Please assure to reboot OLT",
    def_cfg_hit:
        " Defualt the OLT configuration, the system will discard the configuration and auto reboot",
    def_cfg_info:
        " Notice:  After default the OLT configuration, device will be the factory config",
    save_cfg_confirm: " All current settings have been saved and confirmed",
    save_cfg_info:
        " Notice:  Save all current configurations and write them to the device",
    res_cfg_info: " Notice:  You can restore the configuration file",
    bkup_cfg_info: " Notice:  You can backup the configuration file",
    reboot_olt: " Notice:  Click the button, you can restart the OLT",
    view_cfg: " View current config",
    view_cfg_tips:
        " Click to download all current configurations (including unsaved configurations)",

    fullversion: " Full Version Upgrade",
    fv_upgrade_succ:
        " Full version upgrade success, take it effect as restart OLT",
    fv_upgrade_fail: " Full version upgrade falied",
    sys_upgrade_fail: " Upgrade system failed",
    sys_upgrade_succ: " Upgrade system success, take it effect as restart OLT",
    fw_upgrade_fail: " Upgrade firmware failed",
    fw_upgrade_succ: " Upgrade firmware success, take it effect as restart OLT",
    upgrade_buzy: " Upgrade failed, other user upgrading",
    file_header_error: " Upgrade failed, the file header is not correct!",
    upgrade_success: " Upgrade Success, Rebooting device",

    get_data_fail: " Get the data failed",

    onu_cfg: " ONU Setting",
    onu_bw_fail_info: " There's no any bandwidth information in this port",
    sys_run_time: " System Running Time",

    hw_status: " Hardware Status",
    sys_info: " System Informations",
    clk_port_cfg: " Click to setting port",
    ge_port_info: " GE Infomations",
    clk_onu_allow: " Click to setting ONU-allow-list",
    registered_onu: " Registered ",
    pon_info: " PON Informations",
    rstp_port_pri: " Setting rstp port priority",
    rstp_global_info: " Setting rstp gloabal",
    rstp_p_pri_b: " Setting port priority",

    rstp_p_info: " Rstp Port",
    rstp_b_info: " Rstp Bridge",

    no_inb_info: " None outbound interface",
    oub_con_fail: " Connect outbound interface failed",

    if_sure: " Please confirm",

    flush_page_retry: " Please refresh and try it again...",
    sw_port_cfg: " Switch port basic configuration",
    no_more_data: " No more data...",
    no_onu_info: " No more ONU information...",
    add_to_deny: " Add to deny list",
    confirm_del_deny: " Confirm delete this ONU from deny list",
    del_onu: " Delete ONU",
    clk_cancel_cfrm: " Click to cancel confirm",
    clk_cfrm: " Click to confirm",
    input_desc: " Description",
    onu_offline_tips: " The ONU is offline can not be restarted",

    zero_auto_: " if 0 or none:  Auto assign",
    manual_bind: " Manual Add ONU",
    reboot_onu: " Reboot ONU",
    ipaddr_error: " IP address format error",
    ipmask_error: " IP mask format error",

    lang: " Language",
    modify_tips: " There's none modify",
    param_mac: " MAC address parameter error",
    param_onuid: " ONU ID illegal",
    param_error: " illegal parameter",
    time_set: " Time",
    manual_s: " Manual",
    time_days: " Day",
    time_year: " Year",
    time_month: " Month",
    time_day: " Day",
    time_hour: " Hour",
    time_min: " Minute",
    time_sec: " Second",
    time_get_serv: " Get Device Time",
    time_set_local: " Update Local Time",
    notice_time_sync:
        " Notice:  WebGUI's time display maybe different from server, you can press this button for synchronization",
    update_time: " Update Time",
    diff_type_cfg: " the options of different type",
    select_all: " Select All",
    clear_all: " Clear All",

    onu_port_config: " ONU Port Configuration",
    onu_vlan_mode_cfg: " ONU port VLAN mode configuration",
    onu_port_id: " ONU Port ID",
    onu_add_translate: " add vlan translate for ONU",
    onu_del_translate: " delete vlan translate from ONU",
    onu_add_trunk: " add vlan trunk for ONU",
    onu_del_trunk: " delete vlan trunk from ONU",
    vlan_pri_param_error: " VLAN priority parameters incorrect",
    translate_exits: "  VLAN translate is existed",
    trunk_vlanid_range_error: " VLAN list exceed maximum configurable",
    op_id: " ONU Port ID",
    rlds_opt: " down stream rate limit",
    rl_cir: " CIR",
    rl_pir: " PIR",
    rlus_opt: " up stream rate limit",
    loopdetect: " Loop Detect",
    start_vlan_id: " Start VLAN",
    end_vlan_id: " End VLAN",
    op_vlan_mode: " ONU port VLAN mode",
    def_vlan_id: " Default VLAN",
    def_vlan_pri: " Default VLAN Priority",
    new_vlan_pri: " VLAN Priority",
    vlan_pri: " VLAN Priority",
    bandwidth: " Band Width",
    rstp_tips_disable:
        " Global RSTP bridge is not enabled and can not proceed this setting",

    work_temprature: " Work Temperature",
    work_voltage: " Work Voltage",
    transmit_bias: " Transmit Bias",
    transmit_power: " Transmit Power",
    receive_power: " Receive Power",
    refresh: " Refresh",
    onu_optical_diagnose: " ONU Optical Diagnose",
    diag_tools_type: " Diagnose Tools Type",
    dest_ping_ip: " Destination IP",
    diag_ping_intf: " Out Interface",
    diag_ping_count: " PING Count",
    diag_ping_pktsize: " PING Packet Size",
    diag_type: " Ping Test",
    start: " Start",
    select_timezone: " Select Timezone",
    switch_display: " Switch Display Mode",
    service: " Service",
    click_often: " Click too often",
    ntp_ipaddr1: " Preferred IP Address",
    ntp_ipaddr2: " Alternate IP Address",
    ntp_gettime: " Get Time Automatically",
    update_frequency: " Update Frequency",
    alarm: "  Alarm",
    alarm_info: " Alarm Information",
    port_vlan: " Port VLAN",
    pv_vlist_tips:
        'The vlan list can be a single number or a continuous range. The start and end points of the range are separated by " -", and each item is separated by "," .',
    pv_vmode_tips:
        " The vlan mode is allowed to be modified only when the port type is 'hybrid'.",
    add_vlan_list: " Add VLAN",
    del_vlan_list: " Remove VLAN",
    svlan_pri: " SVLAN Priority",
    batch_mgmt_onu: " ONU Batch Management",
    exit_batch_onu: " Exit Batch Management",
    no_select_onu: " No ONU is currently selected",

    onu_batch_upgrade: " ONU Batch Upgrade",
    onu_upgrade_tips:
        'The upgrade type name only consists of English letters, numbers and "  - " ',
    upgrade_type: " Upgrade Type",
    upgrade_type_mgmt: " Upgrade Type Management",
    onu_bind_upgrade_type: " ONU Binding Upgrade Type",
    current_upgrade_type: " Currently Upgrade Types",
    select_upgrade_type: " Select Upgrade Type",
    no_upgrade_type: " No currently available type of upgrade",
    add_onu_type: " Add an ONU upgrade type",
    del_onu_type: " Delete ONU upgrade type",
    onu_upgrade_start:
        " The upgrade has started, The upgrade information is displayed on the alarm information page.",

    igmp: " IGMP",
    fast_leave: " Fast Leave",
    protocol_policy: " Protocol Policy",
    group_aging_time: " Group Aging Time",
    robustness: " Robustness",
    gen_response_time: " General Response Time",
    gen_query_interval: " General Query Interval",
    sp_response_time: " Special Response Time",
    sp_query_interval: " Special Query Interval",
    sp_query_number: " Special Query Number",
    multi_ip: " Multicast IP",
    host_portlist: " Port Members",
    mc_unknown_policy: " Multicast Unknown Policy",
    transparent: " Transparent",
    discard: " Discard",
    mvlan: " Multicast VLAN",
    router_portlist: " Router Port",
    program: " Program",
    program_s: " Program Start",
    program_e: " Program End",
    mode: " Mode",
    query_src_ip: " Query Source IP",
    query_src_mac: " Query Source MAC",
    vid: " Multicast VLAN",
    action: " Multicast Type",
    program_range_tips: " Effective address range:224.0.1.0-239.255.255.255",
    port_list_tips:
        " The routing port is only for the uplink port, 1 for GE1, and 2 for GE2...",

    onu_multicast: " ONU Multicast",
    mc_mode: " multicast mode",
    mc_mac: " multicast MAC",
    group_num_max: " Multicast Max Group",
    tag_mode: " Multicast VLAN Mode",
    mv_conversion_table: " Multicast VLAN Translate Table",
    op_multicast: " ONU Port Multicast",

    onu_alarm: " ONU Alarm",
    mvlan_desc: " Description",
    program_desc: " Program Description",

    batch_cfg_vlan: " Configure Multi-VLANs",

    pon_optical: "Optical Diagnose",
    pon_optical_tips:
        "Here it is the PON Module's RSSI, you need select the location of which ONU you want to trigger",
    loading: "Loading data, please wait ...",
    multicast_table: "Multicast Table",
    static_table: " Static Table",
    tagged_portlist: "Tagged",
    untagged_portlist: "Untagged",
    onu_optical_tips:
        "You need to manually refresh to get the optical power data",

    default_vlan_portlist: "As Default VLAN Port",
    def_vlan_tips:
        "When the port is configured with the default VLAN and is not allowed to be configured.",
    auto_neg_tips:
        "The speed can be configured when the Auto Negonation is disabled.",

    logosize_tips: "LOGO size limit is 240*70px",
    product_name: "Product Model",
    company_info: "Company Information",
    company_name: "Company Name",
    company_addr: "Company Address",
    company_email: "Company Email",
    company_phone: "Contact Number",
    product_name_tips: "Product name cannot exceed 12 characters",
    sysinfo_set: "Logo, model, company information settings",
    goback_devmgmt: "Back to device management",
    imagesize_tips: "The maximum image size is 200kb",

    acl_id_range_error:
        "The ACL ID is incorrect. The basic ACL is 2000-2999, the advanced ACL is 3000-4999, and the link ACL is 5000-5999.",

    action: " Action",
    src_ipaddr: " Source IP",
    src_ipmask: " Source IP Mask",
    dst_ipaddr: " Destination IP",
    dst_ipmask: " Destination IP Mask",
    src_port: " Source Port",
    dst_port: " Destination Port",
    precedence: " Precedence",
    protocol: " Protocol",
    dscp: " DSCP",
    eth_type: " Ethernet Type",
    cos: " COS",
    inner_cos: " Inner COS",
    vlan_id: " VLAN ID",
    inner_vlan_id: " Inner VLAN ID",
    src_mac: " Source MAC",
    dst_mac: " Destination MAC",
    src_mask: " MAC Mask",
    dst_mask: " MAC Mask",
    timerange: "Timerange",
    basic: " Basic ",
    link: " Link ",
    rule: " Rule ",
    acl_mgmt: "ACL Management",
    show: " Show ",
    rule_count: " Rule Count ",
    rule_priority: " Adjust RULE Priority ",
    show_rule: " View Rules ",

    stime: " Start Time ",
    etime: " End Time ",
    day: " Day ",
    sday: "Start Day ",
    eday: "End Day ",
    name: " Name ",
    period: " Period ",
    relative: "Relative",
    absolute: "Absolute",
    state: " State ",
    port_list: " Port List ",

    priority: " Priority ",
    queue_scheduler: " Queue Scheduler ",
    queue: " Queue ",
    weight: " Weight ",
    delete_all: " Delete All ",
    show_detail: " View Details ",
    packet_filter: " Packet Filter ",
    time_range: " Timerange ",
    optional: " Optional ",
    required: " Required ",
    mask: " Mask ",

    preference: " Preference ",
    next_hop: " Next Hop ",
    route_cfg: " Route Configuration ",
    static_route: " Static Route ",
    route: " Route ",
    route_mgmt: " Route Management ",
    ARP: "ARP Table ",
    static_route_tips:
        " Turning off routing will clear all route tables and ARP tables ",
    def_route: " Default Route ",

    loid_mgmt: " LOID List ",
    used: " Used ",
    loid: "LOID",
    ctcver: " CTC Version ",
    onu_perf_info: " ONU Performance ",
    dsDropEvents: "Downstream DropEvents",
    usDropEvents: "Upstream DropEvents",
    dsOctets: "Downstream Octets",
    usOctets: "Upstream Octets",
    dsFrames: "Downstream Frames",
    usFrames: "Upstream Frames",
    dsBroadcastFrames: "Downstream Broadcast Frames",
    usBroadcastFrames: "Upstream Broadcast Frames",
    dsMulticastFrames: "Downstream Multicast Frames",
    usMulticastFrames: "Upstream Multicast Frames",
    dsCrcErrorFrames: "Downstream CRC Errored Frames",
    usCrcErrorFrames: "Upstream CRC Errored Frames",
    dsUndersizeFrames: "Downstream Undersize Frames",
    usUndersizeFrames: "Upstream Undersize Frames",
    dsOversizeFrames: "Downstream Oversize Frames",
    usOversizeFrames: "Upstream Oversize Frames",
    dsFragmentFrames: "Downstream Fragments",
    usFragmentFrames: "Upstream Fragments",
    dsJabberFrames: "Downstream Jabbers",
    usJabberFrames: "Upstream Jabbers",
    dsFrames64Octets: "Downstream Frames 64 octets",
    dsFrames65to127Octets: "Downstream Frames 65 to 127 octets",
    dsFrames128to255Octets: "Downstream Frames 128 to 255 octets",
    dsFrames256to511Octets: "Downstream Frames 256 to 511 octets",
    dsFrames512to1023Octets: "Downstream Frames 512 to 1023 octets",
    dsFrames1024to1518Octets: "Downstream Frames 1024 to 1518 octets",
    usFrames64Octets: "Upstream Frames 64 octets",
    usFrames65to127Octets: "Upstream Frames 65 to 127 octets",
    usFrames128to255Octets: "Upstream Frames 128 to 255 octets",
    usFrames256to511Octets: "Upstream Frames 256 to 511 octets",
    usFrames512to1023Octets: "Upstream Frames 512 to 1023 octets",
    usFrames1024to1518Octets: "Upstream Frames 1024 to 1518 octets",
    dsDiscardFrames: "Downstream Discards",
    usDiscardFrames: "Upstream Discards",
    dsErrorFrames: "Downstream Errors",
    usErrorFrames: "Upstream Errors",
    statusChangeTimes: " Status Change Times ",
    onu_perf_status: " ONU Performance Status ",
    onu_perf_period: "ONU Performance Period ",
    clear_perf: " Clear Performance ",
    curr_perf: " View Current Statistics ",
    history_perf: " View Historical Statistics ",

    file_limit_img: "File format is *.img",
    file_limit_zip: "File format is *.zip",

    ld_status: "Loop Detect Status",
    recover_mode: "Recover Mode",
    recover_manual: "Manual Recover",
    recover_time: "Auto Recover Time",
    detect_interval: "Loop Detect Interval",
    onu_status: "ONU Status",
    ld_port_id: "Loopback Port",
    ld_onu_id: "Loopback ONU",
    loop_detect: " Loop Detection ",
    pon_loop_detect: "PON Loop Detection ",
    ge_loop_detect: " Uplink Loop Detection ",
    ld_info: " Loop Detection Information ",
    loopback: "Loopback",
    port_status: " Port Status ",
    port_isolation: " Port Isolation ",
    pon_isolation_tips: "Set PON port isolation only",

    link_aggregation: "Link Aggregation",
    psc: "Port Selection Criteria",
    member_portlist: " Port Members",
    link_aggregation_tips:
        "Link aggregation group member ports will take effect after configuration",
    trunk_id: " Trunk ID ",

    wan_connect: "WAN Connection",
    index: "Index",
    ipmode: "Channel Mode",
    ctype: "Connection Type",
    igmpproxy: "IGMP Proxy",
    ipproto: "IP Protocol",
    pppoemode: "Authentication Method",
    tagmode: "Enable VLAN",
    reqdns: "Request DNS",
    pridns: "Priamry DNS Server",
    secdns: "Secondary DNS Server",
    portmap: "Port Mapping",
    not_concerned: "Not concerned",
    gateway: "Gateway",
    distance: "Distance(m)",
    last_down_time: "Last Deregister Time",
    last_down_reason: "Last Deregister Reason",

    optical_module: "Optical Module Information",
    portstate: "Port State",
    mstate: "Module State",
    vendor_name: "Vendor Name",
    vendor_oui: "Vendor OUI",
    vendor_rev: "Vendor REV",
    vendor_pn: "Vendor PN",
    vendor_sn: "Vendor SN",
    date_code: "Date",
    vendor_specific: "Vendor Specific",
    module_type: "Module Type",
    max_distance: "Max Distance",
    wave_length: "Wave Length",
    fiber_type: "Fiber Type",
    identifier: "Identifier",
    connector: "Connector",
    encoding: "Encoding",
    cc_base: "CC Base",

    temp_warn_threshold: "Temperature warning threshold(c)",
    temp_alarm_threshold: "Temperature alarm threshold(c)",
    vol_warn_threshold: "Voltage warning threshold(c)",
    vol_alarm_threshold: "Voltage alarm threshold(c)",
    tx_bias_warn_threshold: "Tx bias warning threshold(c)",
    tx_bias_alarm_threshold: "Tx bias alarm threshold(c)",
    tx_power_warn_threshold: "Tx power warning threshold(c)",
    tx_power_alarm_threshold: "Tx power alarm threshold(c)",
    rx_power_warn_threshold: "Rx power warning threshold(c)",
    rx_power_alarm_threshold: "Rx power alarm threshold(c)",

    o_m_state: "Optical Module State",
    o_m_static_info: "Optical Module Static Information",
    o_m_maunu_info: "Optical Module Manufacturer Information",
    o_m_threshold: "Optical Module Threshold Parameter",
    detected: "Detected",
    undetected: "Not Detected",

    conn_error: "Network error, Please check the network connection.",
    logins: "Number of logins",

    rx_octets: "Recieved Bytes",
    rx_frame: "Recieved Frames",
    rx_discard_frame: "Recieved Discard",
    rx_error_frame: "Recieved Error",
    tx_octets: "Transmits Bytes",
    tx_frame: "Transmits Frames",
    tx_discard_frame: "Transmits Discard",
    tx_error_frame: "Transmits Error",

    clear: "Clear",
    mtype: "Calibrated",
    ex_cali: "Externally Calibrated",
    in_cali: "Internal Calibrated",

    onu_wlan: "WLAN",
    encrypt: "Encryption",
    clear_wlan_tips:
        "Note: Clearing the WLAN connection will only clear the configured WLAN connection on the current device.",
    batch_config: "Batch Configuration",
    op_vlan: "ONU Port VLAN",
    wan_count: "Configured",
    wan_count_max: "Maximum support quantity",
    dhcp: "DHCP",
    dhcp_admin: "DHCP Status",
    relay_admin: "Relay Status",
    relay_policy: "Relay Policy",
    standard: "Standard(VLANIF)",
    option60: "Option60",
    option82_admin: " Option82 Status",
    option82_policy: "Option82 Policy",
    reserve: "Reserve ",
    drop: "Drop",
    replace: "Replace",
    option82_circuit: "Sub-Option 1(Circuit ID)",
    option82_remote: "Sub-Option 2(Remote ID)",
    snooping_admin: "Snooping Status",
    chaddr_check: "Client Address Check",
    response_time: "Response Wait Time",
    trust_portlist: "Trust Ports",
    server_ip: " Server Address",
    lease_time: "Lease Time(s)",
    entry_status: "Status",
    snooping_table: "Snooping Table",
    dhcp_relay_tips:
        "DHCP Relay need layer3 support, Do you want to enable it ?",
    route_close_tips:
        "DHCP Relay need layer3 support, Do you want to disable it ?",
    rogue_onu_detection: "Regue ONU Detection",
    detection: "Detection",
    rogueonu_detect_tips:
        "Manual detection starts and the test results are returned to the alarm list.",
    topo: "TOPO",
    no_result: "No Result",
    refreshOrReset: "Refresh / Reset",
    saveAsImage: "Save As Image",
    p2p_flag: "P2P Status",
    rogue_mode: "Rogue ONU",
    port: " Port",
    pon_isolate_portlist: "PON Isolate Port Member",
    uplink_isolate_portlist: "Uplink Isolate Port Member",
    uplink: "Uplink",
    sn: "SN",
    ipaddress_s: "Starting IP Address",
    ipaddress_e: "End IP Address",
    open: " open ",
    close: " close ",
    none_inbound_tips: "No interface available, go to create?",
    server_admin: "Server Status",
    size: "Size",
    open_rt_alarm: "Open real-time alarm",
    close_rt_alarm: "Turn off real-time alerts",
    shortcut: "Shortcut",
    supplier_info: "Supplier Information",

    composeRange(min, max) {
        return `${min} - ${max} characters`;
    }
};

export default en;
